---
language: ruby
script: bundle exec middleman build

env:
  global:
    - GIT_COMMITTER_NAME=digitalnomads
    - GIT_COMMITTER_EMAIL=info@nomadwiki.net
    - GIT_AUTHOR_NAME=digitalnomads
    - GIT_AUTHOR_EMAIL=info@nomadwiki.net
    - secure: "byv67D/fUqjszVE2IuzLaku6IlClY1L6/ZPZRVZSvmm4YLHKornLOTBzMCPgOPCxL3wCc0y3L4FocpXaKAJ+TjesHs4aTQEPplTd0GpwTRDT+hVxwB7jzwuTSqsrBLTfJDR4AEMYn9fSRT+9+kNAINe9LnfHbGB2Tyr/vGAip7g"

before_script:
  - git clone --quiet https://github.com/digitalnomads/digitalnomads.github.io
  - git checkout source

after_success:
  - cd build
  - git add -A
  - git commit -m 'Update'
  - '[ "$TRAVIS_BRANCH" == "source" ] && [ $GH_TOKEN ] && git push --quiet https://$GH_TOKEN@github.com/digitalnomads/digitalnomads.github.io.git master 2> /dev/null'

